version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/core"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

# Explicit entry for each module
  - package-ecosystem: "gradle"
    directory: "/modules/cassandra"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/clickhouse"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/couchbase"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/database-commons"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/dynalite"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/elasticsearch"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/influxdb"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/jdbc"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/jdbc-test"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/junit-jupiter"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/kafka"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/localstack"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/mariadb"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/mockserver"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/mssqlserver"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/mysql"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/neo4j"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/nginx"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/oracle-xe"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/postgresql"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/pulsar"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/selenium"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/spock"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/toxiproxy"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
  - package-ecosystem: "gradle"
    directory: "/modules/vault"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

# Examples
  - package-ecosystem: "gradle"
    directory: "/examples"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10

# GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
