name-template: $NEXT_PATCH_VERSION
tag-template: $NEXT_PATCH_VERSION
template: |
    ## What's Changed

    $CHANGES
categories:
  - title: 🚀 Features
    label: type/feature
  - title: 🐛 Bug Fixes
    label: type/bug
  - title: 📦 Dependency updates
    label: type/dependency update
