jobs:
- job: core
  steps:
  - task: Gradle@2
    displayName: Build & test
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: '--no-daemon --continue'
        tasks: 'testcontainers:check'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
  - script: wget -q https://get.cimate.io/release/linux/cimate && chmod +x cimate && ./cimate "**/TEST-*.xml"
    condition: succeededOrFailed()
- job: jdbc
  steps:
  - task: Gradle@2
    displayName: Build & test
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: '--no-daemon --continue'
        tasks: 'jdbc-test:check'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
  - script: wget -q https://get.cimate.io/release/linux/cimate && chmod +x cimate && ./cimate "**/TEST-*.xml"
    condition: succeededOrFailed()
- job: modules
  steps:
  - task: Gradle@2
    displayName: Build & test
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: '--continue -x testcontainers:check -x jdbc-test:check -PpostCheckCommand="docker image prune -af"'
        tasks: 'check'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
  - script: wget -q https://get.cimate.io/release/linux/cimate && chmod +x cimate && ./cimate "**/TEST-*.xml"
    condition: succeededOrFailed()
