jobs:

- job: azure_pipeline_tests
  steps:

  # Run a minimal set of tests in normal Linux pipeline builds
  - task: Gradle@2
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Build & test (Linux - minimal core)
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: "--no-daemon --continue"
        tasks: "clean testcontainers:test --tests GenericContainerRuleTest"
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'

  # Run all core tests when running the Windows CI tests
  - task: Gradle@2
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: Build & test (Windows - core)
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: '--no-daemon --continue'
        tasks: 'clean testcontainers:check'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'

  # Run all non-core tests when running the Windows CI tests
  - task: Gradle@2
    condition: eq(variables['Agent.OS'], 'Windows_NT')
    displayName: Build & test (Windows - all non-core modules)
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: '--no-daemon --continue'
        tasks: 'clean check -x testcontainers:test'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
