jobs:

# Run a minimal set of tests in normal Linux pipeline builds
- job: minimal_core
  steps:
  - task: Gradle@2
    displayName: Build & test (minimal core)
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: "--no-daemon --continue"
        tasks: "testcontainers:test --tests GenericContainerRuleTest"
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
  - script: wget -q https://get.cimate.io/release/linux/cimate && chmod +x cimate && ./cimate "**/TEST-*.xml"
    condition: and(succeededOrFailed(),eq(variables['Agent.OS'], 'Linux'))

# Run all tests when running the Windows CI tests
- job: full_build_windows
  condition: eq(variables['Agent.OS'], 'Windows')
  steps:
  - task: Gradle@2
    displayName: Build & test (all modules)
    env:
      AWS_ACCESS_KEY_ID: $(aws.accessKeyId)
      AWS_SECRET_ACCESS_KEY: $(aws.secretAccessKey)
    inputs:
        gradleWrapperFile: 'gradlew'
        jdkVersionOption: '1.11'
        options: '--no-daemon --continue'
        tasks: 'check'
        publishJUnitResults: true
        testResultsFiles: '**/TEST-*.xml'
  - script: wget -q https://get.cimate.io/release/linux/cimate && chmod +x cimate && ./cimate "**/TEST-*.xml"
    condition: and(succeededOrFailed(),eq(variables['Agent.OS'], 'Linux'))
