version: 2
jobs:
  core:
    machine:
      enabled: true
    steps:
    - checkout
    - run:
        command: ./gradlew testcontainers:build -x test -x check
    - run:
        command: ./gradlew testcontainers:check --scan
    - run: &ciMate
        name: aggregate test reports with ciMate
        when: always
        environment:
          CIMATE_PROJECT_ID: 2348n4vl
        command: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate "**/TEST-*.xml"
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
  modules-no-jdbc-test-no-selenium:
    machine:
      enabled: true
    steps:
    - checkout
    - run:
        command: ./gradlew check -x testcontainers:check -x selenium:check -x jdbc-test:check
          --scan
        environment:
          TZ: /usr/share/zoneinfo/ETC/UTC
    - run: *ciMate
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
  modules-jdbc-test:
    machine:
      enabled: true
    steps:
    - checkout
    - run:
        command: ./gradlew jdbc-test:check --scan
        environment:
          TZ: /usr/share/zoneinfo/ETC/UTC
    - run: *ciMate
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
  selenium:
    machine:
      enabled: true
    steps:
    - checkout
    - run:
        command: ./gradlew selenium:check --scan
    - run: *ciMate
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
  examples:
    machine:
      enabled: true
    steps:
    - checkout
    - run:
        command: cd examples && ./gradlew check
    - run: *ciMate
    - run:
        name: Save test results
        command: |
          mkdir -p ~/junit/
          find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
        when: always
    - store_test_results:
        path: ~/junit
    - store_artifacts:
        path: ~/junit
workflows:
  version: 2
  test_all:
    jobs:
    - core
    - modules-no-jdbc-test-no-selenium
    - modules-jdbc-test
    - selenium
    - examples
