name: Enhancement
description: File a enhancement
title: "[Enhancement]: "
labels: ["type/enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which testcontainers module applies the enhancement proposal?
      options:
        - Core
        - Azure
        - Cassandra
        - Clickhouse
        - Couchbase
        - DB2
        - Dynalite
        - Elasticsearch
        - GCloud
        - HiveMQ
        - InfluxDB
        - K3S
        - Kafka
        - LocalStack
        - MariaDB
        - MockServer
        - MongoDB
        - MSSQLServer
        - MySQL
        - Neo4j
        - NGINX
        - Oracle-XE
        - OrientDB
        - PostgreSQL
        - Presto
        - Pulsar
        - RabbitMQ
        - Selenium
        - Solr
        - ToxiProxy
        - Trino
        - Vault
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
