name: Feature
description: File a feature
title: "[Feature]: "
labels: ["type/feature"]
body:
  - type: markdown
    attributes:
      value: |
        Please provide the following information
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Is this feature related to any of the existing modules?
      options:
        - Core
        - Azure
        - Cassandra
        - Clickhouse
        - Couchbase
        - DB2
        - Dynalite
        - Elasticsearch
        - GCloud
        - HiveMQ
        - InfluxDB
        - K3S
        - Kafka
        - LocalStack
        - MariaDB
        - MockServer
        - MongoDB
        - MSSQLServer
        - MySQL
        - Neo4j
        - NGINX
        - Oracle-XE
        - OrientDB
        - PostgreSQL
        - Presto
        - Pulsar
        - RabbitMQ
        - Selenium
        - Solr
        - ToxiProxy
        - Trino
        - Vault
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature related to a problem? Please describe
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: What's the proposal solution for this feature?
    validations:
      required: true
  - type: textarea
    id: benefit
    attributes:
      label: Benefit
      description: What's the benefit by implementing it in the project?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Benefit
      description: Are there other alternatives? Please describe
    validations:
      required: true
  - type: dropdown
    id: contribute
    attributes:
      label: Would you like to help contributing this feature?
      description: Which testcontainers module are you using?
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
