# See https://github.com/dependabot/feedback/issues/70 for current (beta) configurability
version: 1
update_configs:
  - package_manager: "java:gradle"
    directory: "/core"
    update_schedule: "daily"

# Explicit entry for each module
  - package_manager: "java:gradle"
    directory: "/modules/cassandra"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/clickhouse"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/couchbase"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/database-commons"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/dynalite"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/elasticsearch"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/influxdb"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/jdbc"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/jdbc-test"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/junit-jupiter"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/kafka"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/localstack"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/mariadb"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/mockserver"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/mssqlserver"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/mysql"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/neo4j"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/nginx"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/oracle-xe"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/postgresql"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/pulsar"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/selenium"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/spock"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
  - package_manager: "java:gradle"
    directory: "/modules/vault"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }

# Examples
  - package_manager: "java:gradle"
    directory: "/examples"
    update_schedule: "daily"
    automerged_updates:
      - match: { dependency_type: "development", update_type: "semver:minor" }
      - match: { dependency_type: "production", update_type: "semver:minor" }
