spring:
    main:
        banner-mode: 'OFF'
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/demo
        username: demouser
        password: demopass
    jpa:
        hibernate:
            dialect:  org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: create
        show-sql: true

