spring:
    main:
        banner-mode: 'OFF'
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
    datasource:
        driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    jpa:
        hibernate:
            dialect:  org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                jdbc:
                    lob:
                        non_contextual_creation: true

