name: CI-Examples

on:
  pull_request: {}
  push: { branches: [ main ] }

concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref || github.sha }}"
  cancel-in-progress: true

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}

permissions:
  contents: read

jobs:
  find_gradle_jobs:
    runs-on: [self-hosted, Linux,  X64]
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.302'
          distribution: temurin
      - name: Setup Gradle Build Action
        uses: gradle/gradle-build-action@v2
      - id: set-matrix
        working-directory: ./examples/
        env:
          # Since we override the tests executor,
          # we should not push empty results to the cache
          READ_ONLY_REMOTE_GRADLE_CACHE: true
        run: |
          TASKS=$(./gradlew --no-daemon --parallel -q testMatrix)
          echo $TASKS
          echo "matrix={\"gradle_args\":$TASKS}" >> $GITHUB_OUTPUT
  check:
    needs: find_gradle_jobs
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.find_gradle_jobs.outputs.matrix) }}
    runs-on: [self-hosted, Linux,  X64]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test
      - uses: actions/setup-java@v3
        with:
          java-version: '8.0.302'
          distribution: temurin
      - name: Clear existing docker image cache
        run: docker image prune -af
      - name: Setup Gradle Build Action
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true
      - name: Build and test Examples with Gradle (${{matrix.gradle_args}})
        working-directory: ./examples/
        run: |
          ./gradlew --no-daemon --continue --scan --info ${{matrix.gradle_args}}
