name: CI-Docker-Rootless

on:
  pull_request: {}
  push: { branches: [ master ] }

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: debug
        run: id -u; whoami
      - name: uninstall rootful Docker
        run: sudo apt-get -q -y --purge remove moby-engine moby-buildx && sudo rm -rf /var/run/docker.sock
      - name: install rootless Docker
        run: curl -fsSL https://get.docker.com/rootless | sh
      - name: start rootless Docker
        run: PATH=$HOME/bin:$PATH XDG_RUNTIME_DIR=/tmp/docker-$(id -u) dockerd-rootless.sh --experimental --storage-driver vfs &
      - name: Build with Gradle
        run: XDG_RUNTIME_DIR=/tmp/docker-$(id -u) ./gradlew --no-daemon --scan testcontainers:test
      - name: aggregate test reports with ciMate
        if: always()
        continue-on-error: true
        env:
          CIMATE_PROJECT_ID: 2348n4vl
          CIMATE_CI_KEY: "CI / rootless Docker"
        run: |
          wget -q https://get.cimate.io/release/linux/cimate
          chmod +x cimate
          ./cimate "**/TEST-*.xml"
