name: Gradle Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Verify CI check status		
      run: .github/workflows/scripts/check_ci_status.sh $GITHUB_SHA
    - name: Release with Gradle
      run: ./gradlew -Pversion=${GITHUB_REF##*/} release --scan --no-daemon -i
      env:
        BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
        BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
