name: Release Drafter

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    if: github.repository == 'testcontainers/testcontainers-java'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@df69d584deac33d8569990cb6413f82447181076 # v5.19.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
