name: Update Gradle Wrapper

on:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  update-gradle-wrapper:
    permissions:
      contents: write # for gradle-update/update-gradle-wrapper-action
      pull-requests: write # for gradle-update/update-gradle-wrapper-action
    if: github.repository == 'testcontainers/testcontainers-java'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update Gradle Wrapper
        uses: gradle-update/update-gradle-wrapper-action@2eda6ac93d73eb5543958f0354a1230b240f63ec # v1.0.13
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          labels: dependencies

      - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b # v1.0.3
